# Generated by Django 4.0.3 on 2022-04-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Season1', models.CharField(max_length=30)),
                ('Sid', models.IntegerField(max_length=5)),
            ],
        ),
    ]
